// FYREN — Supabase schema module
// Applies the SQL schema generated by the agent onto the client's Supabase project.
// Uses the Supabase Management REST API directly (no extra package needed).
//
// Security rules:
//   - service_role_key is decrypted in-memory only, never logged
//   - sanitizeForLog on all error paths
//
// Flow:
//   1. Decrypt the client's Supabase credentials (url + service_role_key)
//   2. Extract the project ref from the URL (https://[ref].supabase.co)
//   3. Get a management API access token (using the service role key)
//   4. Execute the SQL via the DB query API (/rest/v1/rpc or Management API)
//
// Note: Supabase Management API requires a management token (different from service_role_key).
// For direct SQL execution we use the REST /sql endpoint available via the Management API
// (POST https://api.supabase.com/v1/projects/{ref}/database/query).

import { decrypt } from "@/lib/crypto";
import { sanitizeForLog } from "@/server/deploy/utils";

// ============================================================
// Types
// ============================================================

export interface SupabaseSchemaOptions {
  /** Decrypted Supabase project URL, e.g. https://abcdef.supabase.co */
  url: string;
  /** Decrypted service_role_key */
  serviceRoleKey: string;
  /** Raw SQL to execute (CREATE TABLE, RLS policies, indexes, etc.) */
  sql: string;
  /** Progress callback */
  onProgress?: (msg: string) => void;
}

export interface SupabaseSchemaResult {
  projectRef: string;
  tablesCreated: string[];
}

// ============================================================
// Main export
// ============================================================

/**
 * Execute the generated SQL schema on the client's Supabase project.
 * Uses the Supabase REST SQL execution endpoint with the service_role_key.
 */
export async function applySupabaseSchema(opts: SupabaseSchemaOptions): Promise<SupabaseSchemaResult> {
  const { url, serviceRoleKey, sql, onProgress } = opts;

  const projectRef = extractProjectRef(url);
  onProgress?.(`Supabase project ref : ${projectRef}`);

  if (!sql.trim()) {
    onProgress?.("Aucun schema SQL à appliquer — skip");
    return { projectRef, tablesCreated: [] };
  }

  onProgress?.("Application du schema SQL...");

  // Split the SQL into individual statements and execute them in sequence.
  // This is more reliable than running one giant query through the REST API.
  const statements = splitSqlStatements(sql);
  onProgress?.(`${statements.length} statements SQL détectés`);

  const tablesCreated: string[] = [];

  for (let i = 0; i < statements.length; i++) {
    const stmt = statements[i]!.trim();
    if (!stmt) continue;

    onProgress?.(`Exécution statement ${i + 1}/${statements.length}...`);

    await executeSql({
      url,
      serviceRoleKey,
      sql: stmt,
    });

    // Detect table names from CREATE TABLE statements
    const match = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["']?(\w+)["']?/i.exec(stmt);
    if (match?.[1]) {
      tablesCreated.push(match[1]);
    }
  }

  onProgress?.(`Schema appliqué : ${tablesCreated.length} table(s) créée(s)`);

  return { projectRef, tablesCreated };
}

// ============================================================
// Helpers
// ============================================================

/**
 * Decrypt Supabase credentials from service_connections config JSONB.
 * config shape: { encrypted_url: "<base64>", encrypted_service_role_key: "<base64>" }
 */
export async function decryptSupabaseCredentials(
  config: Record<string, string>
): Promise<{ url: string; serviceRoleKey: string }> {
  const encryptedUrl = config["encrypted_url"];
  const encryptedKey = config["encrypted_service_role_key"];

  if (!encryptedUrl) throw new Error("URL Supabase chiffrée introuvable dans la config");
  if (!encryptedKey) throw new Error("service_role_key Supabase chiffré introuvable dans la config");

  const [url, serviceRoleKey] = await Promise.all([decrypt(encryptedUrl), decrypt(encryptedKey)]);
  return { url, serviceRoleKey };
}

/** Extract the project ref (e.g. "abcdef") from https://abcdef.supabase.co */
function extractProjectRef(url: string): string {
  try {
    const hostname = new URL(url).hostname;
    const ref = hostname.split(".")[0];
    if (!ref) throw new Error("ref vide");
    return ref;
  } catch {
    throw new Error(sanitizeForLog(`URL Supabase invalide : ${url}`));
  }
}

/**
 * Split a SQL script into individual statements on `;` while
 * ignoring semicolons inside string literals and `$$` dollar-quoted blocks.
 */
function splitSqlStatements(sql: string): string[] {
  const statements: string[] = [];
  let current = "";
  let inDollarQuote = false;
  let inSingleQuote = false;
  let i = 0;

  while (i < sql.length) {
    const ch = sql[i]!;
    const next = sql[i + 1];

    // Dollar-quoting (common in Postgres functions / RLS policies)
    if (!inSingleQuote && ch === "$" && next === "$") {
      inDollarQuote = !inDollarQuote;
      current += "$$";
      i += 2;
      continue;
    }

    // Single-quote strings (skip escaped quotes '')
    if (!inDollarQuote && ch === "'" && !inSingleQuote) {
      inSingleQuote = true;
      current += ch;
      i++;
      continue;
    }
    if (inSingleQuote && ch === "'" && next === "'") {
      current += "''";
      i += 2;
      continue;
    }
    if (inSingleQuote && ch === "'") {
      inSingleQuote = false;
      current += ch;
      i++;
      continue;
    }

    // Statement separator
    if (!inDollarQuote && !inSingleQuote && ch === ";") {
      const trimmed = current.trim();
      if (trimmed) statements.push(trimmed);
      current = "";
      i++;
      continue;
    }

    current += ch;
    i++;
  }

  const last = current.trim();
  if (last) statements.push(last);

  return statements;
}

interface ExecuteSqlOptions {
  url: string;
  serviceRoleKey: string;
  sql: string;
}

/**
 * Execute a single SQL statement against the Supabase project.
 *
 * Strategy: use the PostgREST RPC endpoint with the service_role_key.
 * For DDL statements (CREATE, ALTER, DROP, etc.), Supabase allows execution
 * via the Management API SQL endpoint when using a service_role_key + management token.
 *
 * Since the Management API requires a separate Supabase access token (not the service_role_key),
 * we fall back to the pg-meta endpoint which is accessible with the service_role_key.
 *
 * Endpoint: POST {url}/rest/v1/rpc/_exec_sql (custom RPC if deployed)
 * Fallback: POST https://api.supabase.com/v1/projects/{ref}/database/query
 *           — requires user's personal Supabase access token, not service_role_key.
 *
 * Most reliable for MVP: use the pg-meta endpoint bundled with every Supabase project.
 * pg-meta endpoint: POST {url}/pg-meta/v1/query
 *
 * This is the same endpoint used by the Supabase Studio SQL editor.
 */
async function executeSql(opts: ExecuteSqlOptions): Promise<void> {
  const { url, serviceRoleKey, sql } = opts;

  // Attempt 1: pg-meta endpoint (works on self-hosted + cloud with service_role_key)
  const pgMetaUrl = `${url.replace(/\/$/, "")}/pg-meta/v1/query`;
  // Attempt 2 endpoint (PostgREST RPC proxy)
  const rpcEndpoint = `${url.replace(/\/$/, "")}/rest/v1/rpc`;

  let res = await fetch(pgMetaUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${serviceRoleKey}`,
      "x-pg-meta-token": serviceRoleKey,
    },
    body: JSON.stringify({ query: sql }),
  });

  if (res.ok) return;

  const pgMetaError = await res.text().catch(() => "");

  // Attempt 2: PostgREST SQL execution via the db-meta proxy
  // Some Supabase versions expose this under /rest/v1/
  res = await fetch(`${rpcEndpoint}/exec_sql`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${serviceRoleKey}`,
      apikey: serviceRoleKey,
      Prefer: "return=minimal",
    },
    body: JSON.stringify({ query: sql }),
  });

  if (res.ok) return;

  const rpcError = await res.text().catch(() => "");

  // Both attempts failed — throw with sanitized messages
  throw new Error(
    sanitizeForLog(
      `Erreur exécution SQL Supabase.\n` +
      `pg-meta: ${pgMetaError.slice(0, 200)}\n` +
      `rpc: ${rpcError.slice(0, 200)}`
    )
  );
}

