// POST /api/deploy
// Triggers the full deploy pipeline for a project:
//   GitHub push → Vercel setup → Supabase schema → persist URLs
//
// Streams progress via SSE (text/event-stream) so the frontend can show live status.
//
// Security:
//   - Clerk auth required
//   - Verifies project ownership before touching any client credentials
//   - Rate limited: 5 deploys per minute
//   - All service tokens decrypted in-memory only
//
// Request body:
//   { projectId: string; schemaSql?: string; repoName?: string; projectName?: string }
//
// SSE events:
//   data: { type: "progress", stage: string, message: string }
//   data: { type: "stage_result", stage: string, status: string, message: string }
//   data: { type: "done", success: boolean, githubUrl, deploymentUrl, projectUrl }
//   data: { type: "error", message: string }

import { auth } from "@clerk/nextjs/server";
import { z } from "zod";
import { rateLimit } from "@/lib/rate-limit";
import { getUserByClerkId } from "@/lib/credits";
import { createServiceClient } from "@/lib/supabase";
import { getSession } from "@/server/agent/session-store";
import { connectSandbox } from "@/server/agent/sandbox-manager";
import { runDeployPipeline, type DeployStage } from "@/server/deploy/index";
import { sanitizeForLog } from "@/server/deploy/utils";

const BodySchema = z.object({
  projectId: z.string().uuid("projectId invalide"),
  /** SQL schema generated by the agent — may be empty */
  schemaSql: z.string().default(""),
  /** GitHub repo name — defaults to project slug */
  repoName: z.string().min(1).optional(),
  /** Vercel project name — defaults to project slug */
  projectName: z.string().min(1).optional(),
});

export const dynamic = "force-dynamic";

export async function POST(req: Request): Promise<Response> {
  // Auth
  const { userId: clerkId } = await auth();
  if (!clerkId) {
    return sseError("Non authentifié", 401);
  }

  // Rate limit: 5 deploys/min
  const rl = rateLimit(`${clerkId}:deploy`, 5, 60_000);
  if (!rl.allowed) {
    return sseError("Trop de requêtes. Réessayez dans une minute.", 429);
  }

  // Parse body
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return sseError("Corps JSON invalide", 400);
  }

  const parsed = BodySchema.safeParse(body);
  if (!parsed.success) {
    return sseError(
      `Données invalides : ${JSON.stringify(parsed.error.flatten())}`,
      400
    );
  }

  const { projectId, schemaSql } = parsed.data;

  // Load user
  const user = await getUserByClerkId(clerkId);
  if (!user) {
    return sseError("Utilisateur introuvable", 404);
  }

  const supabase = createServiceClient();

  // Verify project ownership
  const { data: project } = await supabase
    .from("projects")
    .select("id, slug, sandbox_id, status")
    .eq("id", projectId)
    .eq("user_id", user.id)
    .single();

  if (!project) {
    return sseError("Projet introuvable ou accès refusé", 404);
  }

  // Verify that a sandbox is available (build must have run first)
  if (!project.sandbox_id) {
    return sseError(
      "Aucun sandbox actif pour ce projet. Lancez d'abord un build.",
      422
    );
  }

  const repoName = parsed.data.repoName ?? project.slug;
  const projectName = parsed.data.projectName ?? project.slug;

  // ─────────────────────────────────────────────────────────
  // Set up SSE stream
  // ─────────────────────────────────────────────────────────
  const { readable, writable } = new TransformStream<Uint8Array, Uint8Array>();
  const writer = writable.getWriter();
  const encoder = new TextEncoder();

  function sendEvent(payload: Record<string, unknown>): void {
    const line = `data: ${JSON.stringify(payload)}\n\n`;
    writer.write(encoder.encode(line)).catch(() => {/* client disconnected */});
  }

  // Run the pipeline in the background (don't await)
  (async () => {
    try {
      // Connect to the existing sandbox
      let sandbox = getSession(project.sandbox_id!)?.sandbox ?? null;

      if (!sandbox) {
        sendEvent({ type: "progress", stage: "init", message: "Reconnexion au sandbox E2B..." });
        try {
          sandbox = await connectSandbox(project.sandbox_id!);
        } catch (err) {
          sendEvent({
            type: "error",
            message: sanitizeForLog(`Impossible de connecter au sandbox : ${err instanceof Error ? err.message : String(err)}`),
          });
          await writer.close();
          return;
        }
      }

      sendEvent({ type: "progress", stage: "init", message: "Pipeline de deploy démarré" });

      const result = await runDeployPipeline({
        projectId,
        sandbox,
        schemaSql,
        repoName,
        projectName,
        onProgress: (stage: DeployStage, message: string) => {
          sendEvent({ type: "progress", stage, message: sanitizeForLog(message) });
        },
      });

      // Emit individual stage results
      for (const stageResult of result.stages) {
        sendEvent({
          type: "stage_result",
          stage: stageResult.stage,
          status: stageResult.status,
          message: sanitizeForLog(stageResult.message),
          ...(stageResult.data ?? {}),
        });
      }

      // Final summary
      sendEvent({
        type: "done",
        success: result.success,
        githubUrl: result.githubUrl,
        deploymentUrl: result.deploymentUrl,
        projectUrl: result.projectUrl,
      });
    } catch (err) {
      const msg = sanitizeForLog(err instanceof Error ? err.message : String(err));
      console.error("[POST /api/deploy] unexpected error:", msg);
      sendEvent({ type: "error", message: msg });
    } finally {
      await writer.close().catch(() => {/* already closed */});
    }
  })();

  return new Response(readable, {
    status: 200,
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────

function sseError(message: string, status: number): Response {
  // For pre-flight errors (before SSE stream starts), return JSON
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
